module.exports = {
  ROLE_ADMIN: 1,
  ROLE_USER: 2,

  //FILTER CODE ENUM
  FILTER_BY_MANGA_NAME_ASC: 'FILTER_BY_MANGA_NAME_ASC',
  FILTER_BY_MANGA_NAME_DESC: 'FILTER_BY_MANGA_NAME_DESC',

  FILTER_BY_MANGA_UPDATE_AT_DESC: 'FILTER_BY_MANGA_UPDATE_AT_DESC',
  FILTER_BY_MANGA_UPDATE_AT_ASC: 'FILTER_BY_MANGA_UPDATE_AT_ASC',

  FILTER_BY_MANGA_NUM_VIEWS_DESC: 'FILTER_BY_MANGA_NUM_VIEWS_DESC',
  FILTER_BY_MANGA_NUM_LIKES_DESC: 'FILTER_BY_MANGA_NUM_LIKES_DESC',
  FILTER_BY_MANGA_NUM_FOLLOWS_DESC: 'FILTER_BY_MANGA_NUM_FOLLOWS_DESC',

  FILTER_BY_USER_LIKE_FOLLOW_DATE_DESC: 'FILTER_BY_USER_LIKE_FOLLOW_DATE_DESC',
  FILTER_BY_USER_LIKE_FOLLOW_DATE_ASC: 'FILTER_BY_USER_LIKE_FOLLOW_DATE_ASC',

  //MANGA HIDE STATUS
  MANGA_HIDE_STATUS: 1,
  MANGA_SHOW_STATUS: 0,

  //ACCOUNT STATUS ENUM
  ACCOUNT_STATUS_ACTIVE: 'active',
  ACCOUNT_STATUS_INACTIVE: 'inactive',
  ACCOUNT_STATUS_BLOCKED: 'blocked',

  //STATISTIC ENUM
  STATISTIC_NUM_VIEWS_DESC: 'STATISTIC_NUM_VIEWS_DESC',
  STATISTIC_NUM_LIKES_DESC: 'STATISTIC_NUM_LIKES_DESC',
  STATISTIC_NUM_FOLLOWS_DESC: 'STATISTIC_NUM_FOLLOWS_DESC',
};
