// src/utilities/HandleCode.js

const { NOT_FOUND } = require('http-status-codes');

module.exports = {
  NOT_FOUND: 404,
  SUCCESS: 200,

  //ROLE ENUM
  ROLE_ADMIN: 1,
  ROLE_USER: 2,
  GUEST: 3,

  //ACCOUNT STATUS ENUM
  ACCOUNT_STATUS_ACTIVE: 'active',
  ACCOUNT_STATUS_INACTIVE: 'inactive',
  ACCOUNT_STATUS_BLOCKED: 'blocked',

  //USER STATUS ENUM
  USER_ALREADY_LIKE: 'USER_ALREADY_LIKE_OR_FOLLOW_MANGA',

  //FILTER CODE ENUM
  FILTER_BY_MANGA_NAME_ASC: 'FILTER_BY_MANGA_NAME_ASC',
  FILTER_BY_MANGA_NAME_DESC: 'FILTER_BY_MANGA_NAME_DESC',

  FILTER_BY_MANGA_UPDATE_AT_DESC: 'FILTER_BY_MANGA_UPDATE_AT_DESC',
  FILTER_BY_MANGA_UPDATE_AT_ASC: 'FILTER_BY_MANGA_UPDATE_AT_ASC',

  FILTER_BY_MANGA_NUM_VIEWS_DESC: 'FILTER_BY_MANGA_NUM_VIEWS_DESC',

  FILTER_BY_MANGA_NUM_LIKES_DESC: 'FILTER_BY_MANGA_NUM_LIKES_DESC',

  FILTER_BY_USER_LIKE_FOLLOW_DATE_DESC: 'FILTER_BY_USER_LIKE_FOLLOW_DATE_DESC',
  FILTER_BY_USER_LIKE_FOLLOW_DATE_ASC: 'FILTER_BY_USER_LIKE_FOLLOW_DATE_ASC',
};
