// src/utilities/HandleCode.js

const { NOT_FOUND } = require('http-status-codes');

module.exports = {
  // Path to save file to Firebase storage
  FB_AUTHOR_AVATAR_FOLDER_PATH: 'author_avatar',
  FB_USER_AVATAR_FOLDER_PATH: 'user_avatar',
  FB_COVER_IMAGE_FOLDER_PATH: 'cover_image',
  FB_CHAPTER_IMAGE_FOLDER_PATH: 'chapter_image',
  FB_UPLOAD_FILE_PATH: 'images',

  NOT_FOUND: 404,

  //ROLE ENUM
  ROLE_ADMIN: 1,
  ROLE_USER: 2,

  //ACCOUNT STATUS ENUM
  ACCOUNT_STATUS_ACTIVE: 'active',
  ACCOUNT_STATUS_INACTIVE: 'inactive',
  ACCOUNT_STATUS_BLOCKED: 'blocked',

  //USER STATUS ENUM
  USER_ALREADY_LIKE: 'USER_ALREADY_LIKE_OR_FOLLOW_MANGA',

  //FILTER CODE ENUM
  FILTER_BY_MANGA_NAME_ASC: 'FILTER_BY_MANGA_NAME_ASC',
  FILTER_BY_MANGA_NAME_DESC: 'FILTER_BY_MANGA_NAME_DESC',

  FILTER_BY_MANGA_UPDATE_AT_DESC: 'FILTER_BY_MANGA_UPDATE_AT_DESC',
  FILTER_BY_MANGA_UPDATE_AT_ASC: 'FILTER_BY_MANGA_UPDATE_AT_ASC',

  FILTER_BY_MANGA_NUM_VIEWS_DESC: 'FILTER_BY_MANGA_NUM_VIEWS_DESC',

  FILTER_BY_MANGA_NUM_LIKES_DESC: 'FILTER_BY_MANGA_NUM_LIKES_DESC',

  FILTER_BY_USER_LIKE_FOLLOW_DATE_DESC: 'FILTER_BY_USER_LIKE_FOLLOW_DATE_DESC',
  FILTER_BY_USER_LIKE_FOLLOW_DATE_ASC: 'FILTER_BY_USER_LIKE_FOLLOW_DATE_ASC',

  //UPDATE CODE ENUM
  NO_FIELDS_TO_UPDATE: 'NO_FIELDS_TO_UPDATE',
  EMAIL_EXIST: 'EMAIL_EXIST',
  PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
};
